"""empty message

Revision ID: e8e80a7d5c80
Revises: 
Create Date: 2020-08-02 11:46:17.068895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8e80a7d5c80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('candidate_passcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number_challenges_solved', sa.String(), nullable=True),
    sa.Column('expertise', sa.Integer(), nullable=True),
    sa.Column('expert_in', sa.JSON(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('voted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('users',
    sa.Column('googleId', sa.String(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=True),
    sa.Column('lastName', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('voted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('googleId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('candidates')
    # ### end Alembic commands ###
